events {}

http {
  upstream backend_servers {
    server backend:3000;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend_servers/;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }
  }
}
